[project]
name = "sites-faciles"
description = "Gestionnaire de contenu permettant de créer et gérer un site internet basé sur le Système de design de l'État, accessible et responsive"
authors = [
  "Sébastien Reuiller <sebastien.reuiller@beta.gouv.fr>",
  "Sylvain Boissel <sylvain.boissel@beta.gouv.fr>",
]
maintainers = [
  "Sylvain Boissel <sylvain.boissel@beta.gouv.fr>",
]
readme = "README.md"

[tool.black]
line_length = 119

[tool.pyright]
reportAttributeAccessIssue = false
reportArgumentType = false
reportFunctionMemberAccess = false
reportGeneralTypeIssues = false
reportIncompatibleMethodOverride = false
reportIncompatibleVariableOverride = false
reportOptionalCall = false
reportOptionalMemberAccess = false
reportUnboundVariable = false
